### ISSUE TITLE
Store pid file in work directory

### ISSUE THREAD

**Issue by patcon** [afklm/crowd#11]
Seems that atlassian products are geared toward storing pids in `/var/run`.
https://jira.atlassian.com/browse/BSERV-8707?focusedCommentId=908529&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-908529

I ran into an issue when it seems that crowd is removing the file at some point, and then it gets put back by root.

Would you consider accepting a pull request to keep the pid in `$INSTALL/apache-tomcat/work/crowd.pid`?

**Comment by mrjcleaver** [comment]
+1

**Comment by mrjcleaver** [comment]
Thoughts?

**Comment by mvdkleijn** [comment]
Hmmm... Putting pid files in `/var/run` is a Linux standard. (https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard)

I don't think moving the PID file to the work directory is a good idea. The file being removed is actually a good thing and follows the standard. (it could also just be truncated)

From what you say, the actual problem is the file being recreated (not by Crowd?) under the root user. That's what should be fixed. The init script for the Crowd is being run under the `crowd` user by default.

Sorry for the delay in response by the way.

**Comment by mvdkleijn** [comment]
Considering this fixed in 6c092a29f7fe641f0192cb9857a7cf3c68831fa2
